### ISSUE TITLE
misaligned pointer dereference

### ISSUE THREAD

**Issue by stephanemagnenat** [mcountryman/simd-adler32#11]
Using Rust 1.71 on a Wasm target, I am getting the following error in debug mode:
```
book_web_advanced.js:470 panicked at 'misaligned pointer dereference: address must be a multiple of 0x10 but is 0x3cabc8',
.cargo/registry/src/index.crates.io-6f17d22bba15001f/simd-adler32-0.3.5/src/imp/wasm.rs:103
```

I am using `simd-adler32` indirectly through several dependencies of the `image` crate (for example `png`), and I am compiling the wasm with the following flag: `RUSTFLAGS="-C target-feature=+simd128" `.

My understanding is that we are hitting the recently-merged (1.70) safety check: https://github.com/rust-lang/rust/pull/98112

**Comment by CryZe** [comment]
Seems like this is a bug that I introduced. Interestingly in my other PR for NEON SIMD, I was aware of the unaligned load, weird that I missed it on WASM. I'll do a PR.

**Comment by CryZe** [comment]
You just need `cargo update` in the normal case.

**Comment by mcountryman** [comment]
Right, it's a minor version change.

**Comment by stephanemagnenat** [comment]
Thank you very much for the fast reaction!
