### ISSUE TITLE
file not found for module `util`

### ISSUE THREAD

**Issue by httaotao** [mcountryman/simd-adler32#7]
hello, when I want to run ``` cargo bench```, it shows error ``` file not found for module util``` ,what can i do ? thanks

**Comment by mcountryman** [comment]
Yea, the benchmarks are pretty messed up on the master branch.  Try to checkout the develop branch and benchmark there.

**Comment by mcountryman** [comment]
This is fixed in f7ab31018cc64f7f91880c31cadff017693fb552
