### ISSUE TITLE
Rolling hash support

### ISSUE THREAD

**Issue by Icelk** [mcountryman/simd-adler32#8]
A requirement of support rolling hashes is the ability to remove old bytes.
Can this crate in any way provide that? Are the SIMD implementations prohibiting this? Is it just faster to re-calculate the entire hash instead?
Thanks for this incredible code!

**Comment by mcountryman** [comment]
Thank you 😁 

This crate doesn't currently support removing old bytes.  I misunderstood the requirements of a rolling hash algorithm.  

If it's something you need I might be able to throw in there after some bench-marking to determine the performance implications.  Don't hold your breath though, I've been relatively busy as of late so it may take some time.

**Comment by Icelk** [comment]
It would speed up the rsync-like diffing in my code by... 10x. I however also use other algorithms, so it's not critical.
Thanks for the swift reply.

**Comment by safinaskar** [comment]
@mcountryman
I tried to find some rolling hash in crates.io . So I typed "rolling hash" into search line at crates.io and found this crate. But it seems there is no rolling hash support here. So I wasted some my time. Please remove phrase "rolling hash" from package description and README

**Comment by Icelk** [comment]
Thanks for updating the description!

**Comment by mcountryman** [comment]
No problem!  Sorry for taking so long 😅
